#  Copyright 2025 hlky. All rights reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
"""
CUDA tensor ops module init
"""

from dinoml.backend.cuda.tensor import (
    arange,
    argmax,
    batch_gather,
    cast,
    concatenate,
    concatenate_tanh,
    dynamic_slice,
    expand,
    full,
    gaussian_fourier_projection,
    gather,
    gelu_new,
    get_3d_rotary_pos_embed_allegro,
    get_3d_sincos_pos_embed,
    get_3d_sincos_pos_embed_cogvideox,
    get_2d_sincos_pos_embed_cogview3plus,
    get_2d_sincos_pos_embed,
    get_3d_rotary_pos_embed,
    get_2d_rotary_pos_embed,
    get_2d_rotary_pos_embed_lumina,
    get_1d_rotary_pos_embed,
    get_fourier_embeds_from_boundingbox,
    get_timestep_embedding,
    kdownsample2d_weight,
    cropped_pos_embed,
    fir_downsample2d,
    fir_upsample2d,
    fir_filter_pad2,
    flip,
    identity,
    index_select,
    jagged_to_padded_dense,
    masked_select,
    meshgrid,
    pad,
    padded_dense_to_jagged,
    permute,
    permute021,
    permute0213,
    permute102,
    permute210,
    pixel_shuffle,
    pixel_unshuffle,
    randn,
    relational,
    relative_attention_bias,
    repeat_interleave,
    sinusoidal_positional_embedding,
    slice_reshape_scatter,
    slice_scatter,
    split,
    topk,
    t5_layer_norm,
    where,
    prepare_for_transposed_conv2d,
)

__all__ = [
    "arange",
    "argmax",
    "batch_gather",
    "cast",
    "concatenate",
    "concatenate_tanh",
    "dynamic_slice",
    "expand",
    "full",
    "gaussian_fourier_projection",
    "gather",
    "gelu_new",
    "get_3d_rotary_pos_embed_allegro",
    "get_3d_sincos_pos_embed",
    "get_3d_sincos_pos_embed_cogvideox",
    "get_2d_sincos_pos_embed",
    "get_2d_sincos_pos_embed_cogview3plus",
    "get_3d_rotary_pos_embed",
    "get_2d_rotary_pos_embed",
    "get_2d_rotary_pos_embed_lumina",
    "get_1d_rotary_pos_embed",
    "get_fourier_embeds_from_boundingbox",
    "get_timestep_embedding",
    "kdownsample2d_weight",
    "fir_downsample2d",
    "fir_upsample2d",
    "fir_filter_pad2",
    "flip",
    "cropped_pos_embed",
    "prepare_for_transposed_conv2d",
    "relational",
    "identity",
    "jagged_to_padded_dense",
    "index_select",
    "masked_select",
    "meshgrid",
    "pad",
    "padded_dense_to_jagged",
    "permute",
    "permute021",
    "permute0213",
    "permute102",
    "permute210",
    "pixel_shuffle",
    "pixel_unshuffle",
    "randn",
    "relative_attention_bias",
    "repeat_interleave",
    "sinusoidal_positional_embedding",
    "slice_reshape_scatter",
    "slice_scatter",
    "split",
    "topk",
    "t5_layer_norm",
    "where",
]
